name: Build and deploy FastAPI app to Azure Web App - tradecast

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set Python version (use stable version, NOT 3.13)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies (from backend folder)
      - name: Install dependencies
        run: |
          cd backend
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Upload only backend folder
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend

      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_69F873306FE247B0A85D55ED236AFCBB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55BA787552504FFCA48C4CCAC7AFDDC4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D55F72D40C49491DAB8193377260FD3C }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tradecast'
          slot-name: 'Production'
          package: .
